---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" }}
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    stable.k8s.psg.io/kcm.enabled: "true"
    stable.k8s.psg.io/kcm.provider: "http"
    stable.k8s.psg.io/kcm.email: "{{ .Values.adminEmail }}"
spec:
  tls:
  - secretName: {{ template "name" }}-tls
    hosts:
    - {{ .Values.domain }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /api
        backend:
          serviceName: aspnet-api
          servicePort: 80
      - path: /.well-known/acme-challenge
        backend:
          serviceName: kube-cert-manager
          servicePort: 80
