---
kind: Secret
apiVersion: v1
metadata:
  name: mssql
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  password: {{ print .Values.databasePassword | b64enc | quote }}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mssql
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      namespace: {{ template "name" }}
      labels:
        name: mssql
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      imagePullSecrets:
      - name: acr-image-pull-secret
      containers:
      - name: mssql
        image: {{ .Values.image.registry}}/{{ template "name" }}-mssql:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: ACCEPT_EULA
          value: 'Y'
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: password
---
kind: Service
apiVersion: v1
metadata:
  name: mssql
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    name: mssql
  ports:
  - port: 5432
    targetPort: 5432
