---
kind: Secret
apiVersion: v1
metadata:
  name: postgres
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  {{ if .Values.PostgresPassword }}
  password: {{ .Values.PostgresPassword | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 15 | b64enc | quote }}
  {{ end }}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      namespace: {{ template "name" }}
      labels:
        name: postgres
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: postgres
        image: {{ .Values.image.registry}}/{{ template "name" }}-postgres:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        volumeMounts:
        - name: postgres-auth-secret
          mountPath: /etc/{{ template "name" }}/postgres-auth
          readOnly: true
        ports:
        - containerPort: 80
      volumes:
      - name: postgres-auth-secret
        secret:
          secretName: postgres-auth
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    name: postgres
  ports:
  - port: 5432
    targetPort: 5432
