---
kind: Secret
apiVersion: v1
metadata:
  name: postgres
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  password: {{ print .Values.PostgresPassword | b64enc | quote }}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      namespace: {{ template "name" }}
      labels:
        name: postgres
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      imagePullSecrets:
      - name: acr-image-pull-secret
      containers:
      - name: postgres
        image: {{ .Values.image.registry}}/{{ template "name" }}-postgres:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: {{ template "name" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    name: postgres
  ports:
  - port: 5432
    targetPort: 5432
