apiVersion: v1
kind: List
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: {{namespace}}
    name: frontend
  spec:
    replicas: 3
    template:
      metadata:
        namespace: {{namespace}}
        labels:
          name: frontend
      spec:
        containers:
        - name: frontend
          image: {{registry}}/polykube-frontend:{{version}}
          imagePullPolicy: Always
          ports:
          - containerPort: 80
- kind: Service
  apiVersion: v1
  metadata:
    namespace: {{namespace}}
    name: frontend
  spec:
    selector:
      name: frontend
    ports:
    - port: 80
      targetPort: 80
